name: REUSE Compliance Check

on: [push, pull_request]

jobs:
  reuse-compliance-check:
    runs-on: ubuntu-latest
    if: github.ref_name == github.event.repository.default_branch
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v5
